import {test,expect} from './fixtures';
import {tmpdir} from 'node:os';
import {join} from 'node:path';

test('bulk publishing includes edits; deleting questions preserves personal history',async({page,request},testInfo)=>{
 const errors:string[]=[];
 const title='Library test '+crypto.randomUUID();
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.getByRole('button',{name:'Course library',exact:true}).click();
 await page.getByLabel('Lesson title').fill(title);
 await page.getByLabel('Document',{exact:true}).setInputFiles({name:'lesson.txt',mimeType:'text/plain',buffer:Buffer.from('Eu sunt acasă în fiecare zi.\nNoi avem o casă foarte frumoasă.\nTu mergi la școală dimineața.')});
 const uploaded=page.waitForResponse(r=>r.url().endsWith('/api/materials')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Upload document'}).click();const materialID=(await(await uploaded).json()).id;
 await expect(page.getByRole('textbox',{name:'Teaching text',exact:true})).toHaveValue(/Eu sunt acasă/);
 await expect(page.getByRole('button',{name:'Generate drafts',exact:true})).toBeDisabled();
 await page.getByLabel('I checked this text').check();await page.getByRole('button',{name:'Save and approve text'}).click();
 await expect(page.getByRole('button',{name:'Generate drafts',exact:true})).toBeEnabled();
 await page.getByRole('combobox',{name:'Generation method',exact:true}).selectOption('local');
 let releaseGeneration!:()=>void;
 const generationReady=new Promise<void>(resolve=>{releaseGeneration=resolve});
 await page.route('**/api/materials/*/generate',async route=>{await generationReady;await route.fulfill({status:503,json:{error:'Generation check unavailable. Please retry.'}})},{times:1});
 await page.getByRole('button',{name:'Generate drafts',exact:true}).click();
 try{
  await expect(page.getByRole('status').filter({hasText:'Generating questions…'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Generating…',exact:true})).toBeDisabled();
  await page.locator('.generation-progress').screenshot({path:join(tmpdir(),`romana-loader-${testInfo.project.name}.png`)});
 }finally{releaseGeneration()}
 await expect(page.getByRole('alert')).toContainText('Generation check unavailable. Please retry.');
 await expect(page.locator('.generation-progress')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Generate drafts',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Generate drafts',exact:true}).click();
 await expect(page.locator('article.draft')).toHaveCount(3);
 const third=page.locator('article.draft').nth(2);
 await third.getByRole('button',{name:'Delete question',exact:true}).click();
 await third.getByRole('button',{name:'Cancel',exact:true}).click();
 await expect(page.locator('article.draft')).toHaveCount(3);
 await third.getByRole('button',{name:'Delete question',exact:true}).click();
 await third.getByRole('button',{name:'Confirm deletion',exact:true}).click();
 await expect(page.locator('article.draft')).toHaveCount(2);
 const explanation='Recall sunt: Eu sunt acasă în fiecare zi.';
 await page.locator('article.draft').first().getByRole('combobox',{name:'Exercise type',exact:true}).selectOption('cloze');
 await page.locator('article.draft').first().getByRole('textbox',{name:'Explanation',exact:true}).fill(explanation);
 await page.getByLabel('Select all draft questions',{exact:true}).check();
 await expect(page.getByRole('button',{name:'Publish selected (2)',exact:true})).toBeDisabled();
 await page.getByLabel('I reviewed the selected questions and their answers.',{exact:true}).check();
 await page.getByRole('button',{name:'Publish selected (2)',exact:true}).click();
 await expect(page.locator('article.published')).toHaveCount(2);
 const detail=await(await request.get('/api/materials/'+materialID)).json();
 expect(detail.exercises[0].explanation).toBe(explanation);
 expect(detail.exercises[0].kind).toBe('cloze');expect(detail.exercises[0].options).toEqual([]);
 const exercises=await(await request.get('/api/exercises?materialId='+materialID)).json();
 expect(exercises).toHaveLength(2);expect(exercises[0]).not.toHaveProperty('answers');expect(exercises[0]).not.toHaveProperty('sourceQuote');
 await page.screenshot({path:join(tmpdir(),`romana-library-${testInfo.project.name}.png`),fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Practice this lesson'}).click();await page.getByRole('button',{name:'Start a little practice'}).click();
 await page.getByLabel('Your answer',{exact:true}).fill(' SUNT ');await page.getByRole('button',{name:'Check answer'}).click();
 await expect(page.getByText('Nicely done.',{exact:true})).toBeVisible();await expect(page.getByText('Saved to your history',{exact:true})).toBeVisible();
 await expect(page.locator('.feedback blockquote')).toContainText('Eu sunt acasă');
 await page.reload();await expect(page.locator('.stats strong').first()).toHaveText('1');
 await page.getByRole('button',{name:'Course library',exact:true}).click();await page.getByRole('button',{name:new RegExp(title)}).click();
 const published=page.locator('article.published').first();
 await published.getByRole('button',{name:'Delete question',exact:true}).click();await published.getByRole('button',{name:'Confirm deletion',exact:true}).click();
 await expect(page.locator('article.published')).toHaveCount(1);
 expect(await(await request.get('/api/exercises?materialId='+materialID)).json()).toHaveLength(1);
 await page.getByRole('button',{name:'History',exact:true}).click();
 await expect(page.locator('.history-item')).toHaveCount(1);await expect(page.locator('.history-item')).toContainText(explanation);
 const mixed=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/exercises'&&!new URL(r.url()).search);
 await page.getByRole('button',{name:'Practice',exact:true}).click();const deck=await(await mixed).json();
 await expect(page.getByRole('heading',{name:'A fresh mix for your practice'})).toBeVisible();
 expect(deck.length).toBeGreaterThan(0);expect(deck.length).toBeLessThanOrEqual(10);
 await expect(page.locator('.exercise-prompt')).toHaveCount(0);
 await expect(page.locator('.question-preview')).toHaveCount(0);
 await page.getByRole('button',{name:'Start a little practice'}).click();
 await expect(page.locator('.exercise-prompt')).toHaveText(deck[0].prompt);
 expect(errors).toEqual([]);
});
