import {test,expect} from './fixtures';
import {join} from 'node:path';
import {tmpdir} from 'node:os';

test('admins publish multi-select edits and learners see exact-set feedback and history',async({page,request},testInfo)=>{
 const title='Selection practice '+crypto.randomUUID();
 const upload=await request.post('/api/materials',{multipart:{title,kind:'notes',file:{name:'lesson.txt',mimeType:'text/plain',buffer:Buffer.from('Eu sunt acasă în fiecare zi.')}}});
 expect(upload.ok()).toBe(true);const {id}=await upload.json();
 expect((await request.post('/api/materials/'+id+'/generate',{data:{count:5,mode:'local'}})).ok()).toBe(true);
 await page.goto('/');await page.getByRole('button',{name:'Course library',exact:true}).click();
 await page.getByRole('button',{name:new RegExp(title)}).click();
 const card=page.locator('.question-card');
 await card.getByRole('button',{name:'Edit question',exact:true}).click();
 await card.getByRole('combobox',{name:'Exercise type',exact:true}).selectOption('multi_select');
 const prompt='Select all sentences with correct present-tense agreement.';
 const correct=['Eu sunt acasă.','Noi suntem acasă.'];
 const options=[...correct,'Tu este acasă.','Ei este acasă.'];
 await card.getByRole('textbox',{name:'Question',exact:true}).fill(prompt);
 await card.getByRole('textbox',{name:/^Accepted answers/}).fill(correct.join('\n'));
 await card.getByRole('textbox',{name:/^Answer options/}).fill(options.join('\n'));
 await card.getByRole('textbox',{name:'Explanation',exact:true}).fill('Eu takes sunt and noi takes suntem. Tu takes ești and ei takes sunt.');
 await card.getByText('Learning focus',{exact:true}).click();
 await card.getByRole('combobox',{name:'Skill',exact:true}).selectOption('grammar');
 await card.getByRole('textbox',{name:'Learning target',exact:true}).fill('a fi present agreement');
 await card.getByRole('combobox',{name:'Difficulty',exact:true}).selectOption('medium');
 await page.getByLabel('Select all draft questions',{exact:true}).check();
 await page.getByRole('button',{name:'Publish selected (1)',exact:true}).click();
 await expect(card).toHaveClass(/published/);
 await expect(card.locator('.correct-option')).toHaveCount(2);
 await expect(card.locator('.question-focus')).toContainText('a fi present agreement');
 const {exercises}=await(await request.get('/api/materials/'+id)).json();
 const question=exercises[0];
 expect(question.kind).toBe('multi_select');expect(question.answers).toEqual(correct);
 expect(question.skill).toBe('grammar');expect(question.difficulty).toBe('medium');
 await page.getByRole('button',{name:'Practice this lesson'}).click();
 await expect(page.locator('.exercise-prompt')).toHaveText(prompt);
 await expect(page.getByRole('checkbox')).toHaveCount(4);
 const check=page.getByRole('button',{name:'Check answer',exact:true});
 await expect(check).toBeDisabled();
 await page.getByRole('checkbox',{name:correct[0],exact:true}).check();
 await check.click();
 await expect(page.locator('.feedback-incorrect')).toBeVisible();
 await expect(page.locator('.correct-selections li')).toHaveText(correct);
 await expect(page.getByRole('checkbox').first()).toBeDisabled();
 await page.getByRole('button',{name:'Next question',exact:true}).click();
 await expect(check).toBeDisabled();
 for(const option of correct)await page.getByRole('checkbox',{name:option,exact:true}).check();
 // A lost response must reuse the same attempt ID and save only once.
 await page.route('**/api/attempts',async route=>{expect((await route.fetch()).ok()).toBe(true);await route.fulfill({status:503,json:{error:'Answer response interrupted. Retry checking.'}})},{times:1});
 await check.click();
 await expect(page.getByRole('alert')).toContainText('Answer response interrupted.');
 await check.click();
 await expect(page.locator('.feedback-correct')).toBeVisible();
 expect(await(await request.get('/api/history')).json()).toHaveLength(2);
 await page.screenshot({path:join(tmpdir(),`romana-multi-select-${testInfo.project.name}.png`),fullPage:true});
 await page.getByRole('button',{name:'History',exact:true}).click();
 await expect(page.locator('.history-item')).toHaveCount(2);
 await expect(page.locator('.history-item').first().locator('li')).toHaveText(correct);
 const previous=page.locator('.history-item').nth(1);
 await expect(previous).toContainText('Correct selections:');
 await expect(previous.locator('li')).toHaveText([correct[0],...correct]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('generation shows requested proportions and a persisted shortfall',async({page,request},testInfo)=>{
 const title='Mix summary '+crypto.randomUUID();
 const upload=await request.post('/api/materials',{multipart:{title,kind:'notes',file:{name:'lesson.txt',mimeType:'text/plain',buffer:Buffer.from('Noi suntem acasă în fiecare zi.')}}});
 expect(upload.ok()).toBe(true);const {id}=await upload.json();
 // Only the presentation of a saved summary is simulated here. Provider quotas,
 // replacement reviews and persistence are covered against Go and PostgreSQL.
 let completed=false;
 const note='The full requested mix could not be completed. Only questions that passed both checks were saved.';
 await page.route('**/api/library',async route=>{const response=await route.fetch();const data=await response.json();await route.fulfill({json:{...data,apiEnabled:true}})});
 await page.route('**/api/materials/'+id,async route=>{const response=await route.fetch();const data=await response.json();await route.fulfill({json:completed?{...data,material:{...data.material,generated:true},generationSummary:{requested:{multiple_choice:2,cloze:2,multi_select:1},created:{multiple_choice:2,cloze:1,multi_select:1},shortfall:{multiple_choice:0,cloze:1,multi_select:0},refillAttempted:true,note}}:data})});
 await page.route('**/api/materials/'+id+'/generate',async route=>{completed=true;await route.fulfill({json:{count:4,languageReviewed:true,skipped:[]}})});
 await page.goto('/');await page.getByRole('button',{name:'Course library',exact:true}).click();
 await page.getByRole('button',{name:new RegExp(title)}).click();
 await page.getByRole('combobox',{name:'Maximum drafts',exact:true}).selectOption('20');
 await expect(page.locator('.generation-mix-target')).toContainText('10 single choice');
 await expect(page.locator('.generation-mix-target')).toContainText('8 typed gap');
 await expect(page.locator('.generation-mix-target')).toContainText('2 select all');
 await page.getByRole('combobox',{name:'Maximum drafts',exact:true}).selectOption('5');
 await page.getByRole('button',{name:'Generate drafts',exact:true}).click();
 const summary=page.getByRole('region',{name:'Generation mix',exact:true});
 await expect(summary.getByRole('row')).toHaveCount(4);
 await expect(summary.getByRole('row').filter({hasText:'Typed gap'}).getByRole('cell')).toHaveText(['2','1']);
 await expect(summary).toContainText(note);
 await page.screenshot({path:join(tmpdir(),`romana-generation-mix-${testInfo.project.name}.png`),fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
