{{- if .Values.serviceAccount.create }}
{{- $annotations := deepCopy .Values.serviceAccount.annotations }}
{{- with .Values.serviceAccount.gcpServiceAccount }}
{{- $_ := set $annotations "iam.gke.io/gcp-service-account" . }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "romanian.serviceAccountName" . }}
  labels:
    {{- include "romanian.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
