import {useEffect,useState} from 'react';
import {api,json,type Draft,type DraftEdit,type LibraryData,type MaterialData,type Material} from './api';
const roles:Record<string,string>={notes:'Teaching notes',teacher_corrections:'Teacher corrections',homework:'Homework (reference only)',student_submission:'Learner submission (reference only)'};
type DraftForm={kind:Draft['kind'];prompt:string;answers:string;options:string;explanation:string};
const formFor=(d:Draft):DraftForm=>({kind:d.kind,prompt:d.prompt,answers:d.answers.join('\n'),options:d.options.join('\n'),explanation:d.explanation});
const editFor=(f:DraftForm):DraftEdit=>({kind:f.kind,prompt:f.prompt,answers:f.answers.split('\n').map(s=>s.trim()).filter(Boolean),options:f.kind==='cloze'?[]:f.options.split('\n').map(s=>s.trim()).filter(Boolean),explanation:f.explanation});
export function Library({onPractice}:{onPractice:(material:Material)=>void}){
 const [library,setLibrary]=useState<LibraryData>(),[detail,setDetail]=useState<MaterialData>();
 const [title,setTitle]=useState(''),[kind,setKind]=useState('notes'),[replaces,setReplaces]=useState(''),[file,setFile]=useState<File>();
 const [source,setSource]=useState(''),[reviewed,setReviewed]=useState(false),[count,setCount]=useState(10),[mode,setMode]=useState('local');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [generating,setGenerating]=useState(false);
 const [generationIssues,setGenerationIssues]=useState<{question:number;reason:string}[]>([]);
 const [selected,setSelected]=useState<string[]>([]),[bulkReviewed,setBulkReviewed]=useState(false),[edits,setEdits]=useState<Record<string,DraftForm>>({});
 const refresh=async()=>setLibrary(await api<LibraryData>('/api/library'));
 async function open(id:string,reset=true){const d=await api<MaterialData>('/api/materials/'+id);setDetail(d);setSource(d.material.text||'');setReviewed(false);setBulkReviewed(false);const draftIDs=new Set(d.exercises.filter(e=>e.status==='draft').map(e=>e.id));setSelected(prev=>reset?[]:prev.filter(id=>draftIDs.has(id)));setEdits(prev=>reset?{}:Object.fromEntries(Object.entries(prev).filter(([id])=>draftIDs.has(id))))}
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');setGenerationIssues([]);try{await action()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void api<LibraryData>('/api/library').then(data=>{setLibrary(data);setMode(data.apiEnabled?'api':'local')}).catch(e=>setError(e.message))},[]);
 const locked=!!detail?.material.generated;
 const drafts=detail?.exercises.filter(d=>d.status==='draft')??[];
 const canGenerate=detail&&['notes','teacher_corrections'].includes(detail.material.kind);
 return <main className="library-layout"><div className="library-heading"><div><span className="eyebrow">FROM YOUR LESSONS TO YOUR PRACTICE</span><h1>Your course library.</h1><p>Keep your materials together. Turn useful examples into little moments of recall.</p></div><div className="workflow" aria-label="Workflow">Upload <span>→</span> Review source <span>→</span> Review drafts <span>→</span> Practice</div></div>
 {error&&<div role="alert" className="error banner">{error}</div>}{notice&&<p role="status" className="feedback">{notice}</p>}{!!generationIssues.length&&<details className="generation-issues"><summary>Skipped {generationIssues.length} questions that failed validation</summary><ul>{generationIssues.map(issue=><li key={issue.question}>Question {issue.question}: {issue.reason}.</li>)}</ul><p className="note">Only questions that passed the checks were saved as drafts. Review them before publishing.</p></details>}
 <div className="library-grid"><aside className="library-sidebar"><section className="panel"><span className="eyebrow">ADD A DOCUMENT</span><h2>A lesson to build on</h2><form onSubmit={e=>{e.preventDefault();void run(async()=>{if(!file)throw new Error('Choose a file first');const form=new FormData();form.append('file',file);form.append('title',title);form.append('kind',kind);if(replaces)form.append('replacesId',replaces);const saved=await api<{id:string;duplicate:boolean}>('/api/materials',{method:'POST',body:form});await refresh();await open(saved.id);setNotice(saved.duplicate?'This document is already in your library. Your existing review is preserved.':'Uploaded. Check the extracted text before generating exercises.')})}}>
 <label>Lesson title<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Lesson 12 · At home"/></label>
 <label>Material role<select value={kind} onChange={e=>{setKind(e.target.value);setReplaces('')}}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <label>Version<select value={replaces} onChange={e=>setReplaces(e.target.value)}><option value="">New document</option>{library?.materials.filter(m=>m.kind===kind).map(m=><option key={m.id} value={m.id}>New revision of {m.title} · v{m.revision}</option>)}</select></label>
 <label>Document<input type="file" accept=".docx,.pdf,.txt" required onChange={e=>setFile(e.target.files?.[0])}/></label><p className="note">DOCX, text-based PDF, or TXT · up to 20 MB. Scanned pages need OCR first. Originals stay in your configured file storage.</p>
 <button disabled={busy||!library?.enabled} type="submit">{busy?'Working…':'Upload document'} <span>↑</span></button>
 {library&&!library.enabled&&<p className="error">File storage is disabled on this server.</p>}
 </form></section>
 <section className="document-list" aria-label="Course documents"><h2>Your documents <small>{library?.materials.length??0}</small></h2>{library?.materials.length===0&&<p>No documents yet. Start with a short lesson or your teacher’s corrected examples.</p>}{library?.materials.map(m=><button key={m.id} className={'document '+(detail?.material.id===m.id?'selected':'')} disabled={busy} onClick={()=>void run(()=>open(m.id))}><strong>{m.title}</strong><span>{roles[m.kind]} · v{m.revision}</span><span>{m.publishedCount} ready · {m.draftCount} drafts</span></button>)}</section></aside>
 <section className="panel material-detail" aria-label="Document review">{!detail?<div className="empty-library"><div className="illustration" aria-hidden="true">✎</div><span className="eyebrow">FAMILIAR WORDS. FRESH PRACTICE.</span><h2>Your notes are the starting point.</h2><p>Upload a lesson or open a document to review its text and create exercises you can trust.</p><p className="note">The local generator makes sentence gaps and multiple-choice drafts from Romanian examples. You review every answer before it enters practice.</p></div>:<>
 <div className="step"><span className="eyebrow">{roles[detail.material.kind]} · VERSION {detail.material.revision}</span><a href={'/api/materials/'+detail.material.id+'/original'}>Download original ↗</a></div><h2>{detail.material.title}</h2><p className="note filename">{detail.material.filename}</p>
 <details open={!locked}><summary>1. Review the teaching text {detail.material.reviewed?'· Approved':''}</summary><p>Keep clear Romanian examples and correct answers. Remove instructions, unfinished exercises, and student mistakes. This edits the practice source; the original stays intact.</p><label>Teaching text<textarea className="source-text" value={source} readOnly={locked||!canGenerate} onChange={e=>{setSource(e.target.value);setReviewed(false)}}/></label>
 {!canGenerate?<p className="note">This document is saved for reference. Generate from teaching notes or a separate teacher-corrected document.</p>:locked?<p className="note">This source is preserved with its exercises. Upload a new revision to change it.</p>:<><label className="checkbox"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I checked this text and its Romanian examples are correct.</label><button className="secondary" disabled={busy||!reviewed} onClick={()=>void run(async()=>{await api('/api/materials/'+detail.material.id,json('PATCH',{text:source,reviewed:true}));await open(detail.material.id);await refresh();setNotice('Teaching text approved. You can generate drafts now.')})}>Save and approve text</button></>}
 </details>
 {canGenerate&&<section className="generation"><h3>2. Generate exercise drafts</h3><p>Start with a few examples. Every draft keeps its source sentence so you can check the answer.</p><label>Generation method<select value={mode} disabled={locked||busy} onChange={e=>setMode(e.target.value)}><option value="local">Local · recall only, no AI review</option><option value="api" disabled={!library?.apiEnabled}>AI · generate + Romanian review {library?.apiEnabled?'· configured on the server':'· not configured'}</option></select></label>{mode==='api'&&!locked&&<p className="note">The AI will create questions from this text, then make a separate pass to check the Romanian and answers. Only questions that pass are saved as drafts. Both steps use your configured provider.</p>}<div className="generation-controls" aria-busy={generating}><label>Maximum drafts<select value={count} disabled={locked||busy} onChange={e=>setCount(Number(e.target.value))}>{[5,10,20].map(n=><option key={n}>{n}</option>)}</select></label><button disabled={busy||locked||!detail.material.reviewed||source!==detail.material.text} onClick={()=>void run(async()=>{setGenerating(true);try{const result=await api<{count:number;languageReviewed?:boolean;skipped?:{question:number;reason:string}[]}>('/api/materials/'+detail.material.id+'/generate',json('POST',{count,mode,sendToApi:mode==='api'}));await open(detail.material.id);await refresh();setGenerationIssues(result.skipped??[]);setNotice(`Created ${result.count} drafts${result.languageReviewed?' checked by a separate AI Romanian review':''}. Check each question and answer before publishing.`)}finally{setGenerating(false)}})}>{generating?'Generating…':busy?'Working…':locked?'Drafts generated':'Generate drafts'}</button></div>{generating&&<div className="generation-progress" role="status" aria-live="polite"><span className="generation-spinner" aria-hidden="true"/><div><strong>{mode==='api'?'Generating and checking Romanian…':'Generating questions…'}</strong><p>{mode==='api'?'Creating questions from your lesson and reviewing the language and answers. This can take up to two minutes.':'Turning your lesson examples into practice drafts.'}</p></div></div>}<p className="note">{locked?'Drafts are saved. Upload a new revision to generate another set.':'Fewer drafts may be returned when there are only a few suitable examples. Local generation needs no AI key.'}</p></section>}
 {!!detail.exercises.length&&<div className="draft-list"><h3>3. Review, then publish</h3><p>Published questions are available to everyone in lesson and mixed practice. Your original documents stay private.</p>
 {!!drafts.length&&<section className="bulk-actions" aria-label="Bulk publishing"><label className="checkbox"><input type="checkbox" disabled={busy} checked={selected.length===drafts.length} onChange={e=>{setSelected(e.target.checked?drafts.map(d=>d.id):[]);setBulkReviewed(false)}}/>Select all draft questions</label><span>{selected.length} selected</span><label className="checkbox"><input type="checkbox" disabled={busy||!selected.length} checked={bulkReviewed} onChange={e=>setBulkReviewed(e.target.checked)}/>I reviewed the selected questions and their answers.</label><button disabled={busy||!selected.length||!bulkReviewed} onClick={()=>void run(async()=>{const exercises=drafts.filter(d=>selected.includes(d.id)).map(d=>({id:d.id,...editFor(edits[d.id]??formFor(d))}));const result=await api<{count:number}>('/api/materials/'+detail.material.id+'/publish',json('POST',{exercises,reviewed:true}));await open(detail.material.id,false);await refresh();setNotice(`Published ${result.count} questions. They are ready for practice.`)})}>Publish selected ({selected.length})</button><p className="note">Includes your current edits. All selected questions must have valid answers.</p></section>}
 {detail.exercises.map(d=><DraftEditor key={d.id+':'+d.status} draft={d} form={edits[d.id]??formFor(d)} onChange={form=>{setEdits(prev=>({...prev,[d.id]:form}));setBulkReviewed(false)}} selected={selected.includes(d.id)} onSelect={checked=>{setSelected(prev=>checked?[...prev,d.id]:prev.filter(id=>id!==d.id));setBulkReviewed(false)}} disabled={busy} onSave={async(action)=>{await run(async()=>{await action();await open(detail.material.id,false);await refresh()})}}/>)}</div>}
 {detail.material.publishedCount>0&&<button className="practice-document" disabled={busy} onClick={()=>onPractice(detail.material)}>Practice this lesson <span>{detail.material.publishedCount} questions →</span></button>}
 </>}</section></div></main>
}
function DraftEditor({draft,form,onChange,selected,onSelect,disabled,onSave}:{draft:Draft;form:DraftForm;onChange:(form:DraftForm)=>void;selected:boolean;onSelect:(selected:boolean)=>void;disabled:boolean;onSave:(action:()=>Promise<void>)=>Promise<void>}){
 const [checked,setChecked]=useState(false),[confirmDelete,setConfirmDelete]=useState(false);
 const {kind,prompt,answers,options,explanation}=form;
 const update=(change:Partial<DraftForm>)=>{onChange({...form,...change});setChecked(false)};
 const editable=draft.status==='draft';
 const save=async()=>{await api('/api/drafts/'+draft.id,json('PATCH',editFor(form)))};
 return <article className={'draft '+draft.status}><div className="step"><span className="eyebrow">{kind==='cloze'?'FILL THE GAP':'MULTIPLE CHOICE'}</span><span className="status-tag">{draft.status}</span></div>
 {editable&&<label className="checkbox"><input type="checkbox" aria-label={'Select question: '+draft.prompt} checked={selected} disabled={disabled} onChange={e=>onSelect(e.target.checked)}/>Select question</label>}
 <fieldset disabled={!editable||disabled}><label>Question<textarea value={prompt} onChange={e=>update({prompt:e.target.value})} rows={3}/></label><label>Exercise type<select value={kind} onChange={e=>update({kind:e.target.value as Draft['kind']})}><option value="cloze">Fill in the blank</option><option value="multiple_choice">Multiple choice</option></select></label><div className="answer-grid"><label>Accepted answers<textarea value={answers} onChange={e=>update({answers:e.target.value})} rows={2}/><small>One per line. The first must appear in the source.</small></label>{kind==='multiple_choice'&&<label>Answer options<textarea value={options} onChange={e=>update({options:e.target.value})} rows={3}/><small>One per line; include one correct answer.</small></label>}</div><label>Explanation<textarea value={explanation} onChange={e=>update({explanation:e.target.value})} rows={2}/></label></fieldset>
 <blockquote lang="ro">{draft.sourceQuote}<cite>Source text · line {draft.sourceLine}</cite></blockquote>
 {editable&&<><label className="checkbox"><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>setChecked(e.target.checked)}/>I checked the question, answer, and explanation.</label><div className="draft-actions"><button disabled={disabled||!checked} onClick={()=>void onSave(async()=>{await save();await api('/api/drafts/'+draft.id+'/status',json('POST',{status:'published',reviewed:true}))})}>Save & publish</button><button className="secondary" disabled={disabled} onClick={()=>void onSave(save)}>Save draft</button><button className="text-button" disabled={disabled} onClick={()=>void onSave(async()=>{await api('/api/drafts/'+draft.id+'/status',json('POST',{status:'rejected',reviewed:false}))})}>Reject</button></div></>}
 {confirmDelete?<div className="delete-confirmation"><p>Remove this question from the library and practice? Your saved answers will remain.</p><div className="draft-actions"><button className="danger" disabled={disabled} onClick={()=>void onSave(async()=>{await api('/api/exercises/'+draft.id,{method:'DELETE'})})}>Confirm deletion</button><button className="secondary" disabled={disabled} onClick={()=>setConfirmDelete(false)}>Cancel</button></div></div>:<button className="text-button delete-question" disabled={disabled} onClick={()=>setConfirmDelete(true)}>Delete question</button>}
 </article>
}
