import {useEffect,useState} from 'react';
import {api,json,type LibraryData,type MaterialData,type Material} from './api';
import {QuestionCard,formFor,editFor,type QuestionForm} from './QuestionCard';
const roles:Record<string,string>={notes:'Teaching notes',teacher_corrections:'Teacher corrections',homework:'Homework (reference only)',student_submission:'Learner submission (reference only)'};
export function Library({onPractice}:{onPractice:(material:Material)=>void}){
 const [library,setLibrary]=useState<LibraryData>(),[detail,setDetail]=useState<MaterialData>();
 const [title,setTitle]=useState(''),[kind,setKind]=useState('notes'),[replaces,setReplaces]=useState(''),[file,setFile]=useState<File>();
 const [source,setSource]=useState(''),[count,setCount]=useState(10),[mode,setMode]=useState('local');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [generating,setGenerating]=useState(false);
 const [generationIssues,setGenerationIssues]=useState<{question:number;reason:string}[]>([]);
 const [selected,setSelected]=useState<string[]>([]),[edits,setEdits]=useState<Record<string,QuestionForm>>({});
 const refresh=async()=>setLibrary(await api<LibraryData>('/api/library'));
 async function open(id:string,reset=true){const d=await api<MaterialData>('/api/materials/'+id);setDetail(d);setSource(d.material.text||'');const draftIDs=new Set(d.exercises.filter(e=>e.status==='draft').map(e=>e.id));setSelected(prev=>reset?[]:prev.filter(id=>draftIDs.has(id)));setEdits(prev=>reset?{}:Object.fromEntries(Object.entries(prev).filter(([id])=>d.exercises.some(e=>e.id===id))))}
 async function run(action:()=>Promise<void>):Promise<boolean>{if(busy)return false;setBusy(true);setError('');setNotice('');setGenerationIssues([]);try{await action();return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 useEffect(()=>{void api<LibraryData>('/api/library').then(data=>{setLibrary(data);setMode(data.apiEnabled?'api':'local')}).catch(e=>setError(e.message))},[]);
 const locked=!!detail?.material.generated;
 const drafts=detail?.exercises.filter(d=>d.status==='draft')??[];
 const canGenerate=detail&&['notes','teacher_corrections'].includes(detail.material.kind);
 return <main className="library-layout"><div className="library-heading"><div><span className="eyebrow">FROM YOUR LESSONS TO YOUR PRACTICE</span><h1>Your course library.</h1><p>Keep your materials together. Turn useful examples into little moments of recall.</p></div><div className="workflow" aria-label="Workflow">Upload <span>→</span> Generate <span>→</span> Publish <span>→</span> Practice</div></div>
 {error&&<div role="alert" className="error banner">{error}</div>}{notice&&<p role="status" className="feedback">{notice}</p>}{!!generationIssues.length&&<details className="generation-issues"><summary>Skipped {generationIssues.length} questions that failed validation</summary><ul>{generationIssues.map(issue=><li key={issue.question}>Question {issue.question}: {issue.reason}.</li>)}</ul><p className="note">Only questions that passed the checks were saved as drafts. You can edit them at any time.</p></details>}
 <div className="library-grid"><aside className="library-sidebar"><section className="panel"><span className="eyebrow">ADD A DOCUMENT</span><h2>A lesson to build on</h2><form onSubmit={e=>{e.preventDefault();void run(async()=>{if(!file)throw new Error('Choose a file first');const form=new FormData();form.append('file',file);form.append('title',title);form.append('kind',kind);if(replaces)form.append('replacesId',replaces);const saved=await api<{id:string;duplicate:boolean}>('/api/materials',{method:'POST',body:form});await refresh();await open(saved.id);setNotice(saved.duplicate?'This document is already in your library. Your existing questions are preserved.':'Uploaded. Your lesson is ready to generate questions.')})}}>
 <label>Lesson title<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Lesson 12 · At home"/></label>
 <label>Material role<select value={kind} onChange={e=>{setKind(e.target.value);setReplaces('')}}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <label>Version<select value={replaces} onChange={e=>setReplaces(e.target.value)}><option value="">New document</option>{library?.materials.filter(m=>m.kind===kind).map(m=><option key={m.id} value={m.id}>New revision of {m.title} · v{m.revision}</option>)}</select></label>
 <label>Document<input type="file" accept=".docx,.pdf,.txt" required onChange={e=>setFile(e.target.files?.[0])}/></label><p className="note">DOCX, text-based PDF, or TXT · up to 20 MB. Scanned pages need OCR first. Originals stay in your configured file storage.</p>
 <button disabled={busy||!library?.enabled} type="submit">{busy?'Working…':'Upload document'} <span>↑</span></button>
 {library&&!library.enabled&&<p className="error">File storage is disabled on this server.</p>}
 </form></section>
 <section className="document-list" aria-label="Course documents"><h2>Your documents <small>{library?.materials.length??0}</small></h2>{library?.materials.length===0&&<p>No documents yet. Start with a short lesson or your teacher’s corrected examples.</p>}{library?.materials.map(m=><button key={m.id} className={'document '+(detail?.material.id===m.id?'selected':'')} disabled={busy} onClick={()=>void run(()=>open(m.id))}><strong>{m.title}</strong><span>{roles[m.kind]} · v{m.revision}</span><span>{m.publishedCount} ready · {m.draftCount} drafts</span></button>)}</section></aside>
 <section className="panel material-detail" aria-label="Course document">{!detail?<div className="empty-library"><div className="illustration" aria-hidden="true">✎</div><span className="eyebrow">FAMILIAR WORDS. FRESH PRACTICE.</span><h2>Your notes are the starting point.</h2><p>Upload a lesson or open a document and generate practice questions.</p><p className="note">AI generation creates questions and checks the Romanian in a separate pass. You can edit questions before or after publishing.</p></div>:<>
 <div className="step"><span className="eyebrow">{roles[detail.material.kind]} · VERSION {detail.material.revision}</span><a href={'/api/materials/'+detail.material.id+'/original'}>Download original ↗</a></div><h2>{detail.material.title}</h2><p className="note filename">{detail.material.filename}</p>
 <details><summary>Teaching text · optional edits</summary><p>Romanian examples and English notes guide the AI. Hebrew and other translated annotations are ignored. The original document stays intact.</p><label>Teaching text<textarea className="source-text" value={source} readOnly={locked||!canGenerate} onChange={e=>setSource(e.target.value)}/></label>
 {!canGenerate?<p className="note">This document is saved for reference. Generate from teaching notes or teacher corrections.</p>:locked?<p className="note">This source is preserved with its exercises. Upload a new revision to change it.</p>:<button className="secondary" disabled={busy||source===detail.material.text} onClick={()=>void run(async()=>{await api('/api/materials/'+detail.material.id,json('PATCH',{text:source}));await open(detail.material.id);await refresh();setNotice('Teaching text saved.')})}>Save text</button>}
 </details>
 {canGenerate&&<section className="generation"><h3>Generate exercise drafts</h3><p>Start with a few examples. The AI checks the Romanian and answers before saving your drafts.</p><label>Generation method<select value={mode} disabled={locked||busy} onChange={e=>setMode(e.target.value)}><option value="local">Local · recall only, no AI review</option><option value="api" disabled={!library?.apiEnabled}>AI · generate + Romanian review {library?.apiEnabled?'· configured on the server':'· not configured'}</option></select></label>{mode==='api'&&!locked&&<p className="note">The AI will create questions from this text, then make a separate pass to check the Romanian and answers. Only questions that pass are saved as drafts. Both steps use your configured provider.</p>}<div className="generation-controls" aria-busy={generating}><label>Maximum drafts<select value={count} disabled={locked||busy} onChange={e=>setCount(Number(e.target.value))}>{[5,10,20].map(n=><option key={n}>{n}</option>)}</select></label><button disabled={busy||locked} onClick={()=>void run(async()=>{setGenerating(true);try{if(source!==detail.material.text){await api('/api/materials/'+detail.material.id,json('PATCH',{text:source}))}const result=await api<{count:number;languageReviewed?:boolean;skipped?:{question:number;reason:string}[]}>('/api/materials/'+detail.material.id+'/generate',json('POST',{count,mode}));await open(detail.material.id);await refresh();setGenerationIssues(result.skipped??[]);setNotice(`Created ${result.count} drafts${result.languageReviewed?' checked by a separate AI Romanian review':''}. Publish when ready; you can edit questions later.`)}finally{setGenerating(false)}})}>{generating?'Generating…':busy?'Working…':locked?'Drafts generated':'Generate drafts'}</button></div>{generating&&<div className="generation-progress" role="status" aria-live="polite"><span className="generation-spinner" aria-hidden="true"/><div><strong>{mode==='api'?'Generating and checking Romanian…':'Generating questions…'}</strong><p>{mode==='api'?'Creating questions from your lesson and reviewing the language and answers. This can take up to two minutes.':'Turning your lesson examples into practice drafts.'}</p></div></div>}<p className="note">{locked?'Drafts are saved. Upload a new revision to generate another set.':'Fewer drafts may be returned when there are only a few suitable examples. Local generation needs no AI key.'}</p></section>}
 {!!detail.exercises.length&&<div className="draft-list"><h3>Your lesson questions</h3><p>Published questions are available to everyone in lesson and mixed practice. Original documents are available only to admins.</p>
 {!!drafts.length&&<section className="bulk-actions" aria-label="Bulk publishing"><label className="checkbox"><input type="checkbox" disabled={busy} checked={selected.length===drafts.length} onChange={e=>{setSelected(e.target.checked?drafts.map(d=>d.id):[])}}/>Select all draft questions</label><span>{selected.length} selected</span><button disabled={busy||!selected.length} onClick={()=>void run(async()=>{const exercises=drafts.filter(d=>selected.includes(d.id)).map(d=>({id:d.id,...editFor(edits[d.id]??formFor(d))}));const result=await api<{count:number}>('/api/materials/'+detail.material.id+'/publish',json('POST',{exercises}));await open(detail.material.id,false);await refresh();setNotice(`Published ${result.count} questions. They are ready for practice.`)})}>Publish selected ({selected.length})</button><p className="note">Includes your current edits. All selected questions must have valid answers.</p></section>}
 {detail.exercises.map(d=><QuestionCard key={d.id+':'+d.status} draft={d} form={edits[d.id]??formFor(d)} onChange={form=>{setEdits(prev=>({...prev,[d.id]:form}))}} selected={selected.includes(d.id)} onSelect={checked=>{setSelected(prev=>checked?[...prev,d.id]:prev.filter(id=>id!==d.id))}} disabled={busy} onSave={async(action)=>{return run(async()=>{await action();setEdits({});await open(detail.material.id,false);await refresh()})}}/>)}</div>}
 {detail.material.publishedCount>0&&<button className="practice-document" disabled={busy} onClick={()=>onPractice(detail.material)}>Practice this lesson <span>{detail.material.publishedCount} questions →</span></button>}
 </>}</section></div></main>
}
